### ISSUE TITLE
模块组成 · mqant 的文档库

### ISSUE THREAD

**Issue by liangdas** [liangdas/mqant-chat#38]
http://docs.mqant.com/room_module_composition.html

**Comment by giantss** [comment]
```
$:robot zhongpeng$ go run robot_task.go 
开始压测请等待
Connect...
Network Error : websocket.Dial ws://127.0.0.1:3653: dial tcp 127.0.0.1:3653: connect: connection refused

```

**Comment by giantss** [comment]
上面的问题解决了，是因为服务没有启动。服务启动后运行，报下面的错误。
```
开始压测请等待
Connect...
OnConnectHandler
tabletest/HD_room_say/2 {"Trace":"e4a0c2134e8e7602","Error":"tabletest rpc func(HD_room_say) error interface conversion: interface {} is nil, not string\n ----Stack----\ngoroutine 204 [running]:\ngithub.com/liangdas/mqant/rpc/base.(*RPCServer).runFunc.func3.1(0xc00012a380, 0xc0006d43c0, 0xc0004350e0)\n\t/Users/zhongpeng/go/pkg/mod/github.com/liangdas/mqant@v1.3.4/rpc/base/rpc_server.go:272 +0x11d\npanic(0x158aca0, 0xc0004351d0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\nmqantTest/tabletest.(*tabletest).gatesay(0xc0000ba750, 0x16ff920, 0xc000033980, 0xc0004351a0, 0x18, 0xc00014a000, 0x1ba0008, 0x0)\n\t/Users/zhongpeng/go/src/mqantTest/tabletest/module.go:72 +0x4cd\nreflect.Value.call(0x157fd00, 0xc0005da030, 0x13, 0x162c729, 0x4, 0xc000435110, 0x2, 0x2, 0xc0002e3aa0, 0x100be73, ...)\n\t/usr/local/go/src/reflect/value.go:460 +0x5f6\nreflect.Value.Call(0x157fd00, 0xc0005da030, 0x13, 0xc000435110, 0x2, 0x2, 0x40, 0x1575ec0, 0xc0004351a0)\n\t/usr/local/go/src/reflect/value.go:321 +0xb4\ngithub.com/liangdas/mqant/rpc/base.(*RPCServer).runFunc.func3()\n\t/Users/zhongpeng/go/pkg/mod/github.com/liangdas/mqant@v1.3.4/rpc/base/rpc_server.go:368 +0x13b\ncreated by github.com/liangdas/mqant/rpc/base.","Result":null}

```
